# Site settings
title: Hammer of Thor
email: contact.ctf@milcyber.org
description: "The MCPA competitive hacking team, also known as the Hammer of Thor (HoT), competes in private and public competitions on a regular basis in order to enhance individual technical abilities across the MCPA member base. HoT will execute cyber operations in order to compete and win during specified events as directed by the Team Captain."
url: ""
github_username:  tentpegbob

# Build settings
markdown: redcarpet
pygments: true
baseurl: /projects
paginate: 10
