# Site settings
title: Hammer of Thor
email: contact.ctf@milcyber.org
description: "The MCPA competitive hacking team, also known as the Hammer of Thor (HoT), competes in private and public competitions on a regular basis in order to enhance individual technical abilities across the MCPA member base. HoT competes during specified events as directed by the Team Captain."
url: "https://github.com/MCPA/MCPA.github.io/archive/master.zip"
#github_username:
#twitter_username:

# Build settings
markdown: kramdown
highlighter: pygments
#baseurl: /projects
paginate: 10
